api: fix permission to delete namespace members
shellhub-io/shellhub pull request #1074
Opened 2021-06-29 16:50 UTC by eduardoveiga

2021-06-29 17:27 UTC, noreng-jg submitted a review, later dismissed

2021-06-29 17:52 UTC, otavio requested changes
The change looks fine. However, I'd also to have a test to avoid this kind of error return. Can you add it?

2021-07-01 12:12 UTC, otavio commented on api/nsadm/service.go
> +func (s *service) isNamespaceOwner(ctx context.Context, tenantID, ownerID string) (*models.Namespace, error) {
GetNamespaceForOwner

2021-07-02 01:47 UTC, otavio requested changes

2021-07-02 01:47 UTC, otavio commented on api/nsadm/service.go
> +	if err != nil {
This can be checked on a single line; there are other similar cases too.

2021-07-05 18:46 UTC, otavio commented on api/routes/nsadm.go
> +		}
This is a perfect usecase for the switch.

2021-07-05 20:54 UTC, otavio submitted a review, later dismissed

2021-07-05 22:46 UTC, otavio approved these changes

2021-07-06 11:35 UTC, noreng-jg approved these changes

2021-07-06 11:35 UTC, merged