ui: create component to edit public key
shellhub-io/shellhub pull request #1708
Opened 2022-02-14 19:26 UTC by leonardojoao

Signed-off-by: Leonardo R.S. Joao <leonardo.joao@ossystems.com.br>

2022-02-14 20:58 UTC, noreng-jg approved these changes

2022-02-14 21:10 UTC, otavio requested changes

2022-02-14 21:10 UTC, otavio commented on ui/tests/unit/components/public_key/PublicKeyList.spec.js
> +      currentrole,
currentRole

2022-02-15 12:07 UTC, otavio approved these changes

2022-02-15 12:07 UTC, merged