ui: update public key form to choose filtering
shellhub-io/shellhub pull request #1722
Opened 2022-02-18 14:29 UTC by noreng-jg

2022-02-24 21:49 UTC, otavio requested changes

2022-02-24 21:49 UTC, otavio commented on api/routes/sshkeys.go
> +		return err
```suggestion
		return h.service.AddPublicKeyTag(c.Ctx(), tenant, c.Param(ParamPublicKeyFingerprint), req.Tag)
```

2022-02-24 21:49 UTC, otavio commented on api/routes/sshkeys.go
> +		return err
```suggestion
		return h.service.RemovePublicKeyTag(c.Ctx(), tenant, c.Param(ParamPublicKeyFingerprint), c.Param(ParamTagName))
```

2022-02-24 21:49 UTC, otavio commented on api/routes/sshkeys.go
> +		return err
```suggestion
		return h.service.UpdatePublicKeyTags(c.Ctx(), tenant, c.Param(ParamPublicKeyFingerprint), req.Tags)
```

2022-02-24 21:49 UTC, otavio commented on api/services/sshkeys.go
> +			if exist(tag, key.Filter.Tags) {
I understood the use of lambda here however it is used only once; I'd put the `for` here.

2022-02-24 21:49 UTC, otavio commented on api/services/sshkeys.go
> +				if !exist(tag, tags) {
Same here. 

If desired to use a function (which I am fine too) I'd use https://pkg.go.dev/sort#SearchStrings.

2022-02-24 21:49 UTC, otavio commented on api/services/sshkeys.go
> +				if !exist(tag, tags) {
Same here.

2022-02-24 21:49 UTC, otavio commented on api/services/sshkeys_tags.go
> +	if !exist(tag, tags) {
Here too.

2022-02-24 21:49 UTC, otavio commented on api/services/sshkeys_tags.go
> +	if !exist(tag, key.Filter.Tags) {
And here.

2022-02-24 21:49 UTC, otavio commented on api/store/mongo/device_store_tags.go
> +	}
Something like https://github.com/emirpasic/gods#sets could help.

2022-02-25 00:16 UTC, henrybarreto commented on api/routes/sshkeys.go
> +		return err
Solved on API PR.

https://github.com/shellhub-io/shellhub/pull/1711/files#diff-cfef764ad3b2b7db5e03ce88366635533209cca6671c99f668427b964de580f0R205-R209

2022-02-25 14:11 UTC, otavio approved these changes

2022-02-25 14:11 UTC, merged