api: remove billing store implmentation
shellhub-io/shellhub pull request #2060
Opened 2022-08-05 17:25 UTC by henrybarreto

2022-08-05 19:36 UTC, otavio requested changes

2022-08-05 19:36 UTC, otavio commented on api/store/mongo/store.go
> +	Cache cache.Cache
Maybe use a method so it reduces the number of indirection.

2022-08-05 20:37 UTC, otavio submitted a review, later dismissed

2022-08-08 14:40 UTC, gustavosbarreto approved these changes

2022-08-08 14:52 UTC, merged