ssh: add SFTP support
shellhub-io/shellhub pull request #2094
Opened 2022-08-23 14:57 UTC by henrybarreto

2022-08-25 18:59 UTC, otavio requested changes

2022-08-25 18:59 UTC, otavio commented on agent/sshd/server.go
> +		logrus.Printf("STFP server serve error: %s\n", err)
Shouldn't it use an error?

2022-08-25 18:59 UTC, otavio commented on ssh/main.go
> +	log.SetLevel(log.TraceLevel)
Likely a forgotten change.

2022-08-25 19:08 UTC, henrybarreto commented on ssh/main.go
> +	log.SetLevel(log.TraceLevel)
Exactly!

2022-08-25 21:22 UTC, otavio approved these changes

2022-08-25 21:22 UTC, otavio commented on ssh/server/server.go
> +			"sftp": subsystem.STFPSubsystemHandler(tunnel),
SFTP; check if there is other typos.

2022-08-26 14:56 UTC, otavio approved these changes

2022-08-29 17:20 UTC, otavio commented on ssh/server/server.go
> +	gliderssh "github.com/gliderlabs/ssh"
avoid the rename.

2022-08-29 19:25 UTC, otavio approved these changes

2022-08-29 20:38 UTC, merged