ssh: refactor session and handlers
shellhub-io/shellhub pull request #2106
Opened 2022-09-01 12:37 UTC by henrybarreto

2022-09-10 12:55 UTC, henrybarreto commented
This refactors is completely functional on ShellHub Community.

Connections tested on this refactor:
- [x] Web
- [x] Pty
- [x] Public key
- [ ] Password 
- [x] Exec
    - [x] Exit code propagated
    - [x] Process killed
- [x] Heredoc
    - [x] Process killed
- [x] SCP
- [x] SFTP

2022-09-12 15:18 UTC, otavio requested changes

2022-09-12 15:18 UTC, otavio commented on ssh/pkg/metadata/store.go
> +)
authentication pkg has the same, use it instead.

2022-09-12 15:49 UTC, otavio submitted a review, later dismissed

2022-09-12 19:51 UTC, otavio approved these changes

2022-09-12 19:53 UTC, otavio commented
@henrybarreto please check old agent to ensure it keeps connecting.

2022-09-13 12:39 UTC, merged