agent,api,gateway,pkg,ssh: add public url to access HTTP application on device
shellhub-io/shellhub pull request #2534
Opened 2023-03-02 18:22 UTC by henrybarreto

2023-03-02 18:26 UTC, henrybarreto commented
Related to: https://github.com/shellhub-io/shellhub/issues/90

2023-03-07 21:49 UTC, otavio requested changes

2023-03-07 21:49 UTC, otavio commented on agent/main.go
> +		exit := func(msg string, code int) {
I'd name the `exit` function as `replyError`.

2023-03-07 21:49 UTC, otavio commented on gateway/shellhub.conf
> +}
Newline at end of file.

2023-03-07 21:49 UTC, otavio commented on pkg/api/client/client.go
> +
Is this change intended? It seems as same code just moved to another place. I'd prefer it as another commit or PR.

2023-03-07 21:49 UTC, otavio commented on pkg/api/client/client_public.go
> +
same here.

2023-03-07 21:49 UTC, otavio commented on ssh/main.go
> +		dev, err := tunnel.API.GetDevice("d6c6a5e97217bbe4467eae46ab004695a766c5c43f70b95efd4b6a4d32b33c6e") // TODO: get device UID from request.
Fix TODO.

2023-03-07 21:49 UTC, otavio commented on ssh/main.go
> +			http.Error(w, fmt.Sprintf("failed to get device: %s", err), http.StatusInternalServerError)
prepare a `replyError` function.

2023-03-09 01:43 UTC, otavio submitted a review, later dismissed

2023-03-09 20:27 UTC, merged