passing context to services, creating constants and native error
shellhub-io/shellhub pull request #2927
Opened 2023-06-26 20:42 UTC by henrybarreto

2023-06-26 20:49 UTC, otavio requested changes

2023-06-26 20:49 UTC, otavio commented on cli/services/namespaces.go
> +	MaxNumberDevicesInterprise = -1
Community?

2023-06-29 13:06 UTC, otavio approved these changes

2023-06-29 13:06 UTC, otavio commented
@henrybarreto please fix the CI error so we can merge it.

2023-06-29 13:42 UTC, otavio submitted a review, later dismissed

2023-06-29 13:58 UTC, henrybarreto commented
It is ready to merge

2023-07-05 17:46 UTC, otavio commented on api/store/mongo/migrations.go
> +	lockClient := lock.NewClient(db.Collection("locks", options.Collection().SetWriteConcern(writeconcern.New(writeconcern.WMajority())))) //nolint:staticcheck
Please fix this in a specific commit. Could this be fixes in another PR as this is unrelated.

2023-07-07 18:54 UTC, merged