fix session authentication issues in older agent versions
shellhub-io/shellhub pull request #3143
Opened 2023-10-04 14:16 UTC by heiytor

2023-10-05 16:32 UTC, otavio approved these changes

2023-12-05 11:45 UTC, henrybarreto approved these changes

2023-12-05 11:54 UTC, otavio requested changes

2023-12-05 11:54 UTC, otavio commented on ssh/server/handler/ssh.go
> +	ErrVersionPublicKey   = fmt.Errorf("connections using public keys are not permitted when the agent version is 0.5.x or earlier")
ErrUnsuportedPublicKeyAuth

2023-12-05 17:04 UTC, otavio approved these changes

2023-12-05 17:06 UTC, henrybarreto approved these changes

2023-12-05 17:07 UTC, merged