fix(api): correction to invalid token
shellhub-io/shellhub pull request #3201
Opened 2023-10-26 18:14 UTC by danyecls

when trying to make login using 'user actions' through cloud, the token generated to login is invalid because is not save in cache, this correction is to save token in cache in the AuthGetToken function, this providing a valid token on the user actions screen

2023-10-26 20:39 UTC, heiytor reviewed
What do you think about making the commit message title more descriptive, maybe something similar to 'fix(api): caching user token'?

2023-10-26 21:00 UTC, danyecls commented
> What do you think about making the commit message title more descriptive, maybe something similar to 'fix(api): caching user token'?

I think it's a good idea so I changed the title to the suggested message

2023-10-26 21:30 UTC, otavio requested changes
```
fix(api): Ensure token is cached when getting it from service

When trying to log in through the cloud using 'user actions', the
token generated for login is invalid because it is not saved in the
cache. To resolve this issue, we need to save the token in the 
`AuthGetToken` function, so that a valid token is provided on the
user actions screen.
```

2023-10-30 15:42 UTC, otavio approved these changes

2023-10-30 16:35 UTC, merged