Fix/pagination parameters
shellhub-io/shellhub pull request #3315
Opened 2023-11-27 17:43 UTC by heiytor

2023-11-28 12:05 UTC, otavio submitted a review, later dismissed

2023-11-29 12:36 UTC, otavio requested changes

2023-11-29 12:36 UTC, otavio commented on pkg/api/paginator/query_test.go
> +			expected:    &Query{Page: MinPage, PerPage: 100},
I prefer not to use constants in tests to prevent changes.

2023-11-29 12:54 UTC, henrybarreto approved these changes

2023-11-29 13:35 UTC, otavio approved these changes

2023-11-29 13:35 UTC, merged