test(connman): include test in the syncsslipemaps
shellhub-io/shellhub pull request #3317
Opened 2023-11-29 12:57 UTC by danyecls

2023-11-29 14:06 UTC, heiytor requested changes

2023-11-29 14:06 UTC, heiytor commented on pkg/connman/syncslicemap_test.go
> +			}
I also believe that the `expected` prefix inside the `Expected` struct is redundant.

2023-11-29 14:06 UTC, heiytor commented on pkg/connman/syncslicemap_test.go
> +			}
Here too

2023-11-29 14:06 UTC, heiytor commented on pkg/connman/syncslicemap_test.go
> +			}
Here

2023-11-29 14:06 UTC, heiytor commented on pkg/connman/syncslicemap_test.go
> +			}
And here

2023-12-01 11:38 UTC, danyecls commented on pkg/connman/syncslicemap_test.go
> +			}
changed from t.Error to assert and renamed Expected prefix to 'expectedStatus'

2023-12-01 11:38 UTC, danyecls commented on pkg/connman/syncslicemap_test.go
> +			}
changed to

2023-12-01 11:39 UTC, danyecls commented on pkg/connman/syncslicemap_test.go
> +			}
changed too

2023-12-04 19:44 UTC, henrybarreto approved these changes

2023-12-04 20:04 UTC, heiytor approved these changes

2023-12-05 12:08 UTC, merged