ui: Move snackbarCopy to global and refactor where it is call in code
shellhub-io/shellhub pull request #382
Opened 2020-09-02 20:20 UTC by leonardojoao

This modification improves the use of the snackbarCopy, as it is
declared globally and use of it is done by vuex. And remove unused
variable in DeviceRejectedList component.

2020-09-02 21:39 UTC, otavio approved these changes

2020-09-03 11:39 UTC, noreng-jg requested changes

2020-09-03 11:39 UTC, noreng-jg commented on ui/src/components/device/DeviceAdd.vue
> -      >
When I copy the add device command, a notification of the "tenantID" appears
in it's  place.

2020-09-03 17:45 UTC, noreng-jg approved these changes

2020-09-03 17:54 UTC, otavio approved these changes

2020-09-04 12:46 UTC, gustavosbarreto approved these changes

2020-09-04 12:47 UTC, merged