ui: Update unit tests in device list
shellhub-io/shellhub pull request #422
Opened 2020-09-21 20:41 UTC by noreng-jg

A verification of data-table items in devicelist was added.
This closes #417.

2020-09-23 13:09 UTC, noreng-jg commented
I couldn't find a way to guarantee a comparison of the object fields names individually
in each template tag inside the data-table.
These tests only grant that the device items are loaded as expected.

2020-09-23 13:44 UTC, leonardojoao requested changes
You are verifying the number of items in the list, but you are not verifying the items rendered in the template. It's important to confirm the rendered items with what we expect.

2020-09-23 23:51 UTC, otavio submitted a review, later dismissed

2020-09-24 18:29 UTC, noreng-jg commented
It seems that the slot data in internal template tags of data-table rendered in
each item don't appear mounted in the list components inside
snapshot folder, data can be accessed alternatively with propsData
following this approach.

2020-09-24 19:59 UTC, leonardojoao approved these changes

2020-09-24 23:35 UTC, merged