api: Return the number of devices in get namespace
shellhub-io/shellhub pull request #739
Opened 2021-02-25 21:31 UTC by leonardojoao

2021-02-26 12:18 UTC, otavio submitted a review, later dismissed

2021-02-26 21:48 UTC, otavio requested changes

2021-02-26 21:48 UTC, otavio commented on api/store/mongo/store.go
> +	}
Here we ought to return 0, as this is an error case.

2021-03-01 11:40 UTC, gustavosbarreto requested changes

2021-03-01 11:40 UTC, gustavosbarreto commented on api/store/mongo/store.go
> +func (s *Store) CountDevicesNamespace(ctx context.Context, namespace string) (int, error) {
is this function really needed?

2021-03-01 13:18 UTC, merged