agent: Fixes utmp/wtmp recording on 64-bit systems
shellhub-io/shellhub pull request #791
Opened 2021-03-12 19:53 UTC by sixhills

This change fixes the incorrect formatting of utmp records on some
64-bit systems.

The change writes correct utmp records on:

  32-bit systems where session and time fields in utmp records are 32-bits
  64-bit systems where session and time fields in utmp records are 32-bits
  64-bit systems where session and time fields in utmp records are 64-bits

The only known case where a 64-bit system writes 64-bit session and time
fields is arm64/aarch64 architecture in, for example, Raspberry Pi
64-bit operating systems.

This change has been tested on:
  Debian 10.8.0 32-bit
  Debian 10.8.0 64-bit
  Fedora 33 64-bit
  Gentoo R-Pi 64-bit
  OpenSUSE Leap 15.2 64-bit
  R-Pi OS Latest 32-bit
  R-Pi OS Latest 64-bit
  Ubuntu 20.4 x86 LTS 64-bit
  Ubuntu 20.10 x86 64-bit
  Ubuntu 20.10 R-Pi 32-bit
  Ubuntu 20.10 R-Pi 64-bit

Fixes https://github.com/shellhub-io/shellhub/issues/765

2021-03-12 20:21 UTC, otavio requested changes
@sixhills couldn't the code be designed in a way we'd use a common utmp file and utmp_timeval_time32 and utmp_timeval_time64?

It seems all code is duplicated so it'd be nice to rework it to avoid this.

2021-03-12 20:33 UTC, sixhills commented
Is this what you'd like:
In utmp.go, delete the definition of the Utmpx struct and replace the assigments "u.Tv.Sec, u.Tv.Usec = a.Sec, a.Usec" with a call to a function, say utmpSetTime(u)
In utmp_time??.go, define the appropriate Utmpx struct and define function utmpSetTime.
Do I understand correctly?

2021-03-12 20:37 UTC, otavio commented
Yes. This reduces the code duplication and risk of forgotten unfixed bugs.

2021-03-12 21:42 UTC, sixhills commented
I've made the changes and it works on my development machine.  I'll test on others and update the PR tomorrow.

2021-03-12 22:48 UTC, otavio commented
Awesome @sixhills; thanks for being such a nice partner :-)

2021-03-13 16:11 UTC, otavio approved these changes

2021-03-13 21:28 UTC, sixhills commented
Re-pushed to replace commit message. No code changes.

2021-03-13 21:32 UTC, otavio approved these changes

2021-03-15 17:08 UTC, gustavosbarreto approved these changes

2021-03-15 17:08 UTC, merged