ui: wip
shellhub-io/shellhub pull request #909
Opened 2021-04-30 17:53 UTC by leonardojoao

2021-05-03 16:41 UTC, noreng-jg requested changes

2021-05-03 16:41 UTC, noreng-jg commented on ui/src/components/public_key/KeyFormDialog.vue
> +            Add Rule
Rule?

2021-05-03 16:49 UTC, leonardojoao commented on ui/src/components/public_key/KeyFormDialog.vue
> +            Add Rule
Add {{ action }} Key

2021-05-04 12:25 UTC, noreng-jg approved these changes

2021-05-04 17:03 UTC, merged