api: refuse to create a device if tenant is invadid
shellhub-io/shellhub pull request #980
Opened 2021-05-30 17:56 UTC by eduardoveiga

2021-05-30 20:39 UTC, otavio approved these changes

2021-05-31 14:00 UTC, otavio requested changes
This requires a migration to remove devices in this situation. We may have leftovers and it is important to remove them here.

2021-05-31 14:03 UTC, otavio commented on api/authsvc/service.go
> +	namespace, err := s.store.NamespaceGet(ctx, device.TenantID)
Please add following comment here:
```go
# The order here is critical as we don't want to register devices if the tenant id is invalid
```

2021-05-31 18:09 UTC, otavio reviewed
Please add the migration in this PR so we review it  together.

2021-06-08 02:26 UTC, otavio commented on api/store/mongo/migrations/main.go
> +		migration_24,
here is wrong. This should include just 25.

2021-06-11 14:59 UTC, gustavosbarreto approved these changes

2021-06-11 15:06 UTC, otavio requested changes

2021-06-11 15:06 UTC, otavio commented on api/store/mongo/migrations/main.go
> +		migration_25,
This belongs to the migration patch.

2021-06-11 15:12 UTC, gustavosbarreto requested changes
Why didn't you remove the devices in migration?

2021-06-11 19:49 UTC, merged